---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kyedl.
--- DateTime: 10/7/2023 11:22 PM
---

dofile("C:/Dev/dcs-missions/Moose_pycharm/Moose.lua")
dofile("C:/Dev/dcs-missions/Moose_pycharm/missions/Script.lua")